//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_Ly_San_Bong
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deposit_Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Deposit_Invoice()
        {
            this.Invoices = new HashSet<Invoice>();
        }
    
        public string id_deposit_voice { get; set; }
        public Nullable<System.DateTime> date_deposit { get; set; }
        public Nullable<decimal> deposit_amount { get; set; }
        public string id_account { get; set; }
        public string username { get; set; }
        public Nullable<int> id_time_slot { get; set; }
        public string id_f_pitch { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Football_Pitch Football_Pitch { get; set; }
        public virtual Time_Slot Time_Slot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}
