//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_Ly_San_Bong
{
    using System;
    using System.Collections.Generic;
    
    public partial class Football_Pitch_State_By_Time
    {
        public string id_pitch_state_by_time { get; set; }
        public string state { get; set; }
        public Nullable<decimal> price_by_time { get; set; }
        public Nullable<int> id_time_slot { get; set; }
        public string id_f_pitch { get; set; }
    
        public virtual Football_Pitch Football_Pitch { get; set; }
        public virtual Time_Slot Time_Slot { get; set; }
    }
}
