//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_Ly_San_Bong
{
    using System;
    using System.Collections.Generic;
    
    public partial class Football_Pitch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Football_Pitch()
        {
            this.Deposit_Invoice = new HashSet<Deposit_Invoice>();
            this.Football_Pitch_State_By_Time = new HashSet<Football_Pitch_State_By_Time>();
        }
    
        public string id_f_pitch { get; set; }
        public string name_pitch { get; set; }
        public string type_pitch { get; set; }
        public string address { get; set; }
        public Nullable<decimal> default_price { get; set; }
        public string state { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deposit_Invoice> Deposit_Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Football_Pitch_State_By_Time> Football_Pitch_State_By_Time { get; set; }
    }
}
